version: 2
jobs:
  build:
    docker:
      - image: morxa/fedora-texlive:f29-texlive2018
    steps:
      - checkout
      - run:
          name: Build rulebook
          command: latexmk -pdf rulebook.tex
      - store_artifacts:
          path: rulebook.pdf
  check:
    docker:
      - image: morxa/fedora-texlive:f29-texlive2018
    steps:
      - checkout
      - run:
          name: Run all checks
          command: make check
workflows:
  version: 2
  build_and_check:
    jobs:
      - build
      - check
